-- Script de Migración Inicial de Datos (LEOLCA)
-- (Compatible con Supabase SQL Editor)

-- 1. INSERTAR CLIENTES
INSERT INTO clientes (organizacion_id, nombre_razon_social, nombre_contacto, direccion, codigo_postal, telefono, correo) VALUES
    ((SELECT id FROM organizaciones LIMIT 1), 'SR. HERMELINDO RIVEROS LOPEZ', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'OSCAR GABRIEL ANDRADE', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'OSCAR GABRIEL ANDRADE', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'JOSE MIGUEL HUERTA GARCIA', 'JOSE MIGUEL HUERTA GARCIA', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'JOSE MIGUEL HUERTA', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'REYES VERGARA', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'MARCO ANTONIO FERNANDEZ', '', 'PACHUCA HIDALGO', '', '771 509 0716', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'LEONEL NAVA VARGAS', '', '', '', '797 106 6888', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'SIRILO ORTEGA LUNA', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ALFREDO SANCHEZ', '', 'TULANCINGO HGO.', '', '771 266 7692', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'JORGE VILLEGAS', 'GRUPO INTEROCEANICO TERRESTRE', 'JUCHITAN OAXACA MEXICO', '', '951 157 1007', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ING. IVAN VARGAS', '', 'ZACATLAN PUEBLA', '', '222 132 7067', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'MARTIN CASTAÑEDA', '', '', '', '241 195 0805', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'JOSE ANTONIO LOPEZ AMADOR', '', '', '', '442 467 1061', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ARTEMIO RIVAS', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'MANUEL HERNANDEZ VARGAS', '', '', '', '776 110 8200', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'MOISES HERNANDEZ', '', 'CHIGNAHUAPAN PUEBLA', '', '797 102 1473', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'EVA CORTEZ ORTEGA', '', '', '', '776 101 1063', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'JOSE ARMANDO JIMENEZ MALDONADO', '', '', '', '797 155 2240', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'VENANCIO DOMINGUEZ', 'EXPRES DOAVAL', '', '', '776 767 0499', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'VICTOR ALFONSO GONZALEZ MAIZ', '', '', '', '775 103 4457 CONTACTO CESAR LIRA', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'JAIME GARCIA', '', '', '', '442 327 3548', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'DANIEL CORTEZ', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'MIGUEL VARGAS', '', 'PEDRO ESCOBEDO QUERETARON MEX.', '', '442 157 0865', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ABEL HERNANDEZ', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'YOVANY VALDEZ', '', '', '', '55 3030 2266', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'FRANCISCO GONZALEZ', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'MANUEL MELENDEZ VENTURA', '', '', '', '773 103 0083', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'JESUS BONILLA', '', '', '', '5573749806', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'MIGUEL DAVILA', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'FERNANDO AGUILAR', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'GAVINO MALDONADO', '', '', '', '776 110 4595', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'BERNARDO VERGARA', '', '', '', '55 3648 9630', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'PASCUAL AGUILAR', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'MA. DE LOURDES GARRIDO GALINDO', '', '', '', '5624 3861 88', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'RAFAEL ROJAS', 'POTRILLOS', '', '', '776 767 8645', 'facturas_rrc@hotmail.com'),
    ((SELECT id FROM organizaciones LIMIT 1), 'EDUARDO GARRIDO', '', '', '', '797 112 5749', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'FRANCISCO ORTEGA BARRERA', 'MORGAN', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ARMANDO PONCE PLATA', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'JAIME EMILIO MUÑOZ RAMOS', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'MARCIAL CASTRO', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'RICARDO MARTINEZ', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'NALLELY DE LOS ANGELES VEGA ROLDAN', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'Jose Carlos Ruiz', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'EFRAIN SANCHEZ', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'BRYAN HERNANDEZ', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'JOSE MALDONADO', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'REYMUNDO PEREZ', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ALBERTO EZPINOZA IRAPUATO', '', '', '', '462 590 8532', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'DARIO GONZALEZ MARTINEZ', 'DARIO GONZALEZ MARTINEZ', 'CONOCIDO LA BOVEDA ACAXOCHITLAN HIDALGO MEX', '43734', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ANGEL ROJAS', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'JUAN ALCANTARA', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'TRANSPORTES DYDE', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'DIANA O VICTOR AGUILAR LOPEZ', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'CESAR DURANTE PONCE', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'HERIBERTO ROLDAN LOZADA', 'HERIBERTO ROLDAN LOZADA', 'RAYON 18, CENTRO ACAXOCHITLAN HIDALGO MEXICO', '43730', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ERICK ZAMORA SERRANO', 'ERICK ZAMORA SERRANO', 'CALLE NUEVA No. EXT.8 CENTRO SANTA ANA NOPALUCAN, TLAXCALA, MEXICO', '90135', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'LAURA NAYELI ZALETA MATIAS', 'LAURA NAYELI ZALETA MATIAS', 'LOC. LA BOVEDA S/N LA BOVEDA, ACAXOCHITLAN, HIDALGO, MEXICO', '43734', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'KAERI ESTRADA CRUZ', 'KAERI ESTRADA CRUZ', 'CAPULIN PTE 100 CUANALA, JUAN C. BONILLA, PUEBLA, MEXICO', '72640', '', 'transportesllc_2012@hotmail.com'),
    ((SELECT id FROM organizaciones LIMIT 1), 'ANABERTHA ESCALONA ALVARADO', 'ANABERTHA ESCALONA ALVARADO', 'SINALOA 14, HUITZILA TIZAYUCA, HIDALGO, MEXICO', '43820', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ALVARO AGUILAR VAZQUEZ', 'ALVARO AGUILAR VAZQUEZ', 'PRINCIPAL S/N LA ESTACION, AHUAZOTEPEC, PUELA, MEXICO', '73191', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'GUSTAVO ORTEGA', 'LOGISTICA GO CARGO', 'ZURITA 55, TEQUISISTLAN TEZOYUCA, EDO MEX. MEXICO', '56020', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'NOE CORTEZ ORTEGA', 'NOE CORTEZ ORTEGA', 'CARRETERA A CUAUTEPEC 20, EL CALVARIO AHUAZOTEPEC, PUEBLA, MEXICO', '73180', '', 'noecortez1990@outlook.com'),
    ((SELECT id FROM organizaciones LIMIT 1), 'RAMON ROLDAN', 'AUTOFLETES3RS', 'HACIENDA DE OJUELOS MZ 832 LT 15, EMILIO CHUAYFET NEZAHUALCOYOTL, EDO. MEX. MEXICO', '57130', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'MA. MATILDE MEJIA CASTRO', 'MA. MATILDE MEJIA CASTRO', 'CUATROCIENEGAS 115, GUADALUPE AHMSA MONCLOVA, COAHUILA, MEXICO', '25750', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'CONSTANTINO PABLO ISLAS HERNANDEZ', 'CONSTANTINO PABLO ISLAS HERNANDEZ', '20 DE NOVIEMBRE 21, COL: CENTRO VENTA GRANDE, HUAUCHINANGO, PUEBLA MEXICO', '73160', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'RAFAEL AGUILAR VAZQUEZ', 'RAFAEL AGUILAR VAZQUEZ', 'PRINCIPAL S/N LA ESTACION, AHUAZOTEPEC, PUELA, MEXICO', '73180', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'JESUS GARCIA ORTIZ', 'JESUS GARCIA ORTIZ', 'AHUAZOTEPEC, PUEBLA, MEXICO', '73180', '', 'jesgar81@hotmail.com'),
    ((SELECT id FROM organizaciones LIMIT 1), 'LUCINA YANERI CRUZ GARCIA', 'LUCINA YANERI CRUZ GARCIA', 'CARRETERA ESTATAL PACHUCA-CD.-SAHAGÚN KM. 29, ACELOTLA DE OCAMPO ZEMPOALA, HIDALGO, MEXICO', '43835', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ESTEBAN GONZALEZ ORTEGA', 'ESTEBAN GONZALEZ ORTEGA', 'AV. DE LOS TECNICOS 14, EL PARAISO HUAUCHINANGO, PUEBLA, MEXICO', '73176', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ELIZABETH MUÑOZ DOMINGUEZ', 'ELIZABETH MUÑOZ DOMINGUEZ', 'EMILIANO ZAPATA S/N, CENTRO AHUAZOTEPEC, PUEBLA, MEXICO', '73180', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'IRENE YAÑEZ MARQUEZ', 'IRENE YAÑEZ MARQUEZ', 'MORELOS ESQUINA CON CALLE NARANJA S/N , CENTRO ACATLAN, HIDALGO, MEXICO', '43540', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'NICOLAS URIBE GAYOSSO', 'NICOLAS URIBE GAYOSSO', 'FRANCISCO CRAVIOTO SUR 69, CENTRO AHUAZOTEPEC, PUEBLA, MEXICO', '73180', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ALONSO CUEVAS', 'TRANSPORTADORA GRUPO GYM', 'CARRETERA QUERETARO S.L.P  KM 21 3, COL: ROSA DE JAUREGUI QUERETARO, QUERETARO, MEXICO', '76220', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'GRUPO LOZAGUI SA DE CV', 'GRUPO LOZAGUI', 'MELCHOR OCAMPO 117, CENTRO TULANCINGO DE BRAVO HIDALGO MEXICO', '43600', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'OSCAR ORTEGA DE LA FUENTE', 'OSCAR ORTEGA DE LA FUENTE', 'ADOFO MATEOS Mz. 9, Lt.16, GUSTAVO BAZ PRADA ECATEPEC DE MORELOS, ED. MEX, MEXICO', '55050', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'EFREN MUÑOZ AGUILAR', 'EFREN MUÑOZ AGUILAR', 'AVENIDA FRANCISCO CRAVIOTO SUR 101, COL: SEGUNDA SECCION AHUAZOTEPEC, PUEBLA, MEXICO', '73180', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'MARIA AIDA GARCIA BACA', 'MARIA AIDA GARCIA BACA', 'FUENTES DE LOS FRAILES 11 COL: MORATILLA PUEBLA, PUEBLA, MEXICO', '72110', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'DANIELA GARRIDO GUERRA', 'DANIELA GARRIDO GUERRA', '5 De Febrero No. 305, COL: CENTRO TULANCINGO DE BRAVO HIDALGO MEXICO', '43600', '', 'danielagarridoguerra@gmail.com'),
    ((SELECT id FROM organizaciones LIMIT 1), 'RENE CORTEZ  ORTEGA', 'RENE CORTEZ ORTEGA', 'CAMINO A CUAUTEPEC 1 EL CALVARIO AHUAZOTEPEC, PUEBLA, MEXICO', '73180', '', 'renecortez2010@hotmail.com'),
    ((SELECT id FROM organizaciones LIMIT 1), 'HEBERTO HERNANDEZ', '', '', '', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ALVARO ORTEGA BARRERA', 'ALVARO ORTEGA BARRERA', 'MIGUEL HIDALGO 8, CENTRO AHUZOTEPEC, PUEBLA, MEXICO', '73180', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'LEONARDO ISLAS AVILA', 'LEONARDO ISLAS AVILA', 'ALVARO OBREGON 16, CENTRO SANTA MONICA, EPAZOYUCAN, HIDALGO, MEXICO', '43590', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'RODOLFO LUNA LUNA', 'RODOLFO LUNA LUNA', 'CALLE PRINCIPAL S/N, METEPEC ZACATLAN, PUEBLA, MEXICO', '73310', '797 116 7130', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'MARIA LAURA LOPEZ LUNA', 'MARIA LAURA LOPEZ LUNA', 'POSTE 70 S/N ZACATLAN, PUEBLA, MEXICO', '73310', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ALEXA AGUILAR SUAREZ', 'ALEXA AGUILAR SUAREZ', 'TOMAS ALVA EDISON 1, COL: ESTRELLA TULANCINGO DE BRAVO HIDALGO MEXICO', '43660', '', 'transportes.vosa@outlook.com'),
    ((SELECT id FROM organizaciones LIMIT 1), 'ANTONIO GONZALEZ ORTIZ', 'ANTONIO GONZALEZ ORTIZ', 'CARR.TULANCINGO HUASCA KM 11, COL: METEPEC 1 ACATLAN, HIDALGO, MEXICO', '43540', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ARDELIO SALAS ISLAS', 'ARDELIO SALAS ISLAS', 'Calle Francisco I. Madero S/N COL: CENTRO AHUAZOTEPEC, PUEBLA, MEXICO', '73180', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'IVAN GONZALEZ GUTIERREZ', 'IVAN GONZALEZ GUTIERREZ', 'AV. DE LOS TECNICOS 14, EL PARAISO HUAUCHINANGO, PUEBLA, MEXICO', '73176', '776 105 7542', 'ivanglezgtz_14@hotmail.com'),
    ((SELECT id FROM organizaciones LIMIT 1), 'FILIBERTA MUÑOZ RODRIGUEZ', 'FILIBERTA MUÑOZ RODRIGUEZ', 'LOS PINOS S/N, DE PUEBLA SANTA ANA NOPALUCAN, TLAXCALA, MEXICO', '90139', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'PEDRO DOMINGUEZ ROSAS', 'PEDRO DOMINGUEZ ROSAS', 'AV. DON LUIS ESQ. ALFA No. 6, FRACC. BELLA VISTA HUAUCHINANGO, PUEBLA, MEXICO', '73160', '776 767 8094', 'transportesdominguez2@outlook.com'),
    ((SELECT id FROM organizaciones LIMIT 1), 'GERMAN MORALES OBREGON', 'GERMAN MORALES OBREGON', 'CISNES NORTE MANZANA 17 LOTE 5, VILLAS DE PACHUCA PACHUCA DE SOTO, HIDALGO, MEXICO', '42083', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'JAIME ROJAS CRUZ', 'JAIME ROJAS CRUZ', 'CAMINO A CUAUTEPEC S/N, EL CALVARIO AHUAZOTEPEC, PUEBLA, MEXICO', '73180', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ARTEMIO MARTINEZ CASTILLA', 'ARTEMIO MARTINEZ CASTILLA', 'CARRETERA 350, COL: LAS LAJAS ZACATLAN, PUEBLA, MEXICO', '73310', '', 'artemiomartinez25c@gmail.com'),
    ((SELECT id FROM organizaciones LIMIT 1), 'LUCIANO MALDONADO MORALES', 'LUCIANO MALDONADO MORALES', '3A SECCION AHUACATLA AHUAZOTEPEC, PUEBLA, MEXICO', '73180', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'GENARO GONZALEZ GUZMAN', 'GENARO GONZALEZ GUZMAN', 'MORELOS No. Ext. 23-C BERISTAIN AHUAZOTEPEC PUEBLA MEXICO', '73190', '', 'beris3g@hotmail.com'),
    ((SELECT id FROM organizaciones LIMIT 1), 'EFRAIN MARTINEZ MARTINEZ', 'EFRAIN MARTINEZ MARTINEZ', 'JUSTO SIERRA 22, COL: AHUAZOTEPEC AHUAZOTEPEC, PUEBLA, MEXICO', '73180', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ESMERALDA SOLEDAD CORTES FLORES', 'ESMERALDA SOLEDAD CORTES FLORES', 'GUMERSINDO M HERNANDEZ 27 TLAXCO, TLAXCALA, MEXICO', '90250', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'CESAR  VALDEZ MARTINEZ', 'CESAR  VALDEZ MARTINEZ', 'IGNACIO ZARAGOZA ORIENTE 12, COL: CENTRO AHUAZOTEPEC, PUEBLA, MEXICO', '73180', '', 'noe_wiskly@hotmail.com'),
    ((SELECT id FROM organizaciones LIMIT 1), 'EDITH HERNANDEZ DOMIGUEZ', 'EDITH HERNANDEZ DOMIGUEZ', 'PRIVADA DE INDEPENDENCIA S/N, COL: EL POSITO ZACATLAN, PUEBLA, MEXICO', '73310', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ZENON VARGAS LOPEZ', 'ZENON VARGAS LOPEZ', 'CONOCIDO S/N FERRERIA DE APULCO, METEPEC, HIDALGO, MEXICO', '43411', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'AMANDO ORTEGA DE LA FUENTE', 'AMANDO ORTEGA DE LA FUENTE', 'ADOLFO LOPEZ MATEOS MZ 9 LT 16 ECATEPEC DE MORELOS, ED. MEX, MEXICO', '55050', '', 'facturacion.ortega@gmail.com'),
    ((SELECT id FROM organizaciones LIMIT 1), 'MARGARITA SOTO DOMINGUEZ', 'MARGARITA SOTO DOMINGUEZ', 'IGNACIO ZARAGOZA PONIENTE, 3, CENTRO AHUAZOTEPEC, PUEBLA, MEXICO', '73180', '', 'sotodominguez450@gmail.com'),
    ((SELECT id FROM organizaciones LIMIT 1), 'JAVIER GAYOSSO OLVERA', 'JAVIER GAYOSSO OLVERA', 'FRANCISCO CESAR MORALES MZ 123, SANTA MARTHA ACATITLA IZTAPALAPA, CD MEXICO, MEXICO', '_0951', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'HELIBERIO ORTEGA MARTINEZ', 'HELIBERIO ORTEGA MARTINEZ', 'CLAVEL 39, SANTA ROSA DE JAUREGUI QUERETARO, QUERETARO, MEXICO', '76220', '', ''),
    ((SELECT id FROM organizaciones LIMIT 1), 'ALDO ROJAS RAMIREZ', 'ALDO ROJAS RAMIREZ', 'CORREGIDORA, 8, CENTRO BERISTAIN AHUAZOTEPEC PUEBLA MEXICO', '73180', '', '');

-- 2. INSERTAR MATERIALES
INSERT INTO productos (organizacion_id, tipo, tipo_item, unidad, nombre, costo, precio_unitario) VALUES
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'BORDA DELANTERA', 2064, 2064),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'BORDA TRASERA', 2236, 2236),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PORTA PLACA', 88.14999999999999, 88.14999999999999),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'BASE PARA ESTRIBO', 924.5, 924.5),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PTR 4*4 PARA ESTRIBO', 2016, 2016),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PORTALODERA', 442.90000000000003, 442.90000000000003),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SEPARADOR CENTRO', 408.5, 408.5),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'JUEGO ALETAS (ALERONES)', 2113.45, 2113.45),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PUENTES PARA PLANCHA', 425, 425),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PLACA P/QUINTA', 5203, 5203),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PAR/PESTAÑAS', 220.16, 220.16),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PAR FLEJES', 145, 145),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CAJA DE HERRAMIENTAS', 4751.5, 4751.5),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'KIT BASE P/TANQUE', 344, 344),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PAR BASES PARA PORTALLANTAS', 266.6, 266.6),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PUENTES PARA SUSPENSIÓN', 967.5, 967.5),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'BUCHACAS', 55.9, 55.9),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'BASE PARA PATÍN', 2322, 2322),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'JUEGO BASE L P/PATIN', 709.5, 709.5),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CANAL PARA PERCHA 1.10 m', 709.5, 709.5),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PLACA REF PARA PERCHA 30 X 15', 838.5, 838.5),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PLACA REF PARA PLATO 7.6 X 20', 301, 301),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'BUCHACAS PARA PATIN', 86, 86),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'JALON P/ GANCHO DE ARRASTRE', 4224.75, 4224.75),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CON RIEL', 5805, 5805),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'BUCHACAS P/ BURRO', 89.22500000000001, 89.22500000000001),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'ESTACA P/BURRO', 655.75, 655.75),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'TUBO 1 1/4', 136, 136),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PLACA 1/4', 20137, 20137),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SOLERA DE 1/2"* 6" *12M', 6482, 6482),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CANAL U DE 6" *12M', 5060.56, 5060.56),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'GANCHO PARA LAZO 1/2', 33.333, 33.333),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SOLERAS DE 3/8" *2', 799, 799),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SOLERA PORTALLANTAS 1/2*3', 266.225, 266.225),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'REDONDO PORTALLANTAS Y JALON 1"', 140, 140),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'REDONDO DE 5/8 X 6MTS P/REDILAS', 43, 43),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'ANGULO 1/8 *1  1/2 PORTALLANTAS', 59, 59),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'ANGULO 2 X 2 X 3/16', 172.072, 172.072),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SOLERA 1 1/2"*3/16 P/ESQUINEROS', 67.462, 67.462),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SOLERA PLACA 1/8 X 2 X 6MTS', 43, 43),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'TUBO DE 2 CED 40', 203.406, 203.406),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'TUBO MEC 3/4 CED 40', 116.39, 116.39),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'TUBO 1  1/2 CED 40', 183.4, 183.4),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CARGADORES DE 4"', 577, 577),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PERNO REY HOLLAND', 1409.3999999999999, 1409.3999999999999),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CINTA REFLEJANTE', 2436, 2436),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'ROTULACIÓN', 927.9999999999999, 927.9999999999999),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'TANQUE DE AIRE', 1081.12, 1081.12),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'MATRACA CORREDIZA', 307.4, 307.4),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SIN MATRACAS', 0, 0),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'KIT DE ABS Y CONEXIONES 2 EJES', 23000, 23000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'KIT DE ABS Y CONEXIONES 3 EJES', 27000, 27000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SUSPENSIÓN FLEET MASTER', 23118, 23118),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SUSPENSIÓN AMPRO', 23118, 23118),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SUSPENSIÓN HENDRICKSON', 35844, 35844),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SUSPENSIÓN ALTA HENDRICKSON', 43700, 43700),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SUSPENSION HJ ALTA', 28477.999999999996, 28477.999999999996),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'EJES AMPRO', 22231.399999999998, 22231.399999999998),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'EJES FLEET MASTER', 20099.99, 20099.99),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PATÍN HOLLAND', 13461.4, 13461.4),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PATÍN HJ', 5798.81, 5798.81),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PATIN AMPRO', 5336, 5336),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CO2', 905, 905),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'MICROTUBULAR', 945, 945),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CONSUMIBLE', 638, 638),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'TOPES HULE 3 BARRENOS', 82, 82),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'DISCOS DE CORTADORA', 46.4, 46.4),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'DISCOS LAMINADOS #7', 75.39999999999999, 75.39999999999999),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'DISCOS DE DESBASTE #9', 40.599999999999994, 40.599999999999994),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CARDA DE COPA TRENZADA', 104.39999999999999, 104.39999999999999),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'HOJAS DE LIJA', 23.2, 23.2),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CABLEADO', 827, 827),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'LODERAS', 670, 670),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'BANDEROLAS', 400.2, 400.2),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'LUCES', 8939.64, 8939.64),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'TORNILLOS', 2000, 2000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'MATERIAL COMPLEMENTARIO', 2500, 2500),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PIJAS/BROCAS', 2552, 2552),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PISO DE MADERA DE PINO', 22000, 22000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PISO DE MADERA DE ENCINO', 22000, 22000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PISO DE PLÁSTICO CAFÉ', 35000, 35000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PISO DE PLASTICO NEGRO', 36182.72, 36182.72),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PISO LAMINADO', 28224, 28224),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PISO LAMINADO CON BASE DE MADERA', 50000, 50000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PISO LAMINADO CON BASE DE PLÁSTICO', 63500, 63500),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PISO ANTIDERRAPANTE', 22000, 22000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'GANCHO PREMIER 8 BARRENOS', 12979.24, 12979.24),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'GANCHO PREMIER BESTIA 6 BARRENOS', 21892.68, 21892.68),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'GANCHO HOLLAND 8/10 BARRENOS', 6948.4, 6948.4),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SISTEMA RETRÁCTIL', 15000, 15000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'REFUERZOS', 10000, 10000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CANDADO', 461, 461),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SIN SISTEMA RETRÁCTIL', 0, 0),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'REDILAS DE 70 CM', 35000, 35000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'REDILAS DE 75 CM', 35500, 35500),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'REDILAS DE 80 CM', 36000, 36000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'REDILAS DE 1M', 42000, 42000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CONCHA LAMINADA A 1.20 M', 6160, 6160),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CONCHA LAMINADA A 1.70 M', 6891, 6891),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CONCHA LAMINADA 1.50 M', 7500, 7500),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CONCHA A 2.35 M', 11750, 11750),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CONCHA LISA REFORZADA A 1.20 M', 7536, 7536),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CONCHA A 1.40 M', 8800, 8800),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CONCHA A 2.00 MTS', 10000, 10000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CONCHA A 1.50 M', 7680, 7680),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'BURRO LAMINADO A 1.50', 7250, 7250),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'BURRO LAMINADO A 1.80', 8700, 8700),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'BURRO LAMINADO A 1.20 M', 5800, 5800),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CONCHA A 1 M', 6240, 6240),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'BURRO DE MADERA 1.20 M', 4515, 4515),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CONCHA 1.10 M', 5891, 5891),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'RINES DE ACERO', 1391.97, 1391.97),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'RINES DE ALUMINIO', 4268.8, 4268.8),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'LLANTAS CEREX', 3586, 3586),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'LLANTAS FIRESTONE', 8790, 8790),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'LLANTAS ROYAL BLACK', 5600, 5600),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'LLANTAS BF GOODRICH', 11750, 11750),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'LLANTAS EUDEMON', 5400, 5400),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'LLANTAS CHINAS', 4000, 4000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'LLANTAS VALIANT', 3581, 3581),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'LLANTAS AMULET', 5400.01, 5400.01),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'POLINERA  GRANDE', 6000, 6000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'POLINERA CON PUERTA', 10000, 10000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CAJA DE HRRTAS CHICA', 9500, 9500),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'BICiCLETERA', 5000, 5000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PORTALLANTAS EXTRA', 3500, 3500),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CANASTILLA', 8000, 8000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PLAFONES AMBAR', 400, 400),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PLAFONES ROJO', 400, 400),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PLAFONES DE CARRITO AMBAR LATERALES', 168.2, 168.2),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PLAFONES DE CARRITO ROJOS LATERALES', 168.2, 168.2),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PATA DE ELEFANTE', 3250, 3250),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'POLINERA CON BICICLETERA', 8000, 8000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CAJA AUXILIARES', 1500, 1500),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'LODERA DE CENTRO', 874, 874),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'SISTEMA PSI', 20000, 20000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'JALON', 3768, 3768),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'POLINERA ATRAVESADA', 6000, 6000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'CANDADOS', 1450, 1450),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'MUTI MODAL', 50000, 50000),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'BARRENADO SOBRE CHASIS', 1250, 1250),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PLAFONES DE CARRITO AMBAR P/ESTRIBO', 168.2, 168.2),
    ((SELECT id FROM organizaciones LIMIT 1), 'bien', 'materia_prima', 'PZA', 'PLAFONES DE CARRITO ROJOS P/ESTRIBO', 168.2, 168.2);
