server {
    listen 80;

    location / {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, PATCH, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization, apikey, x-client-info, x-supabase-api-version';
            add_header 'Access-Control-Max-Age' '86400';
            return 204;
        }

        proxy_hide_header 'Access-Control-Allow-Origin';
        proxy_hide_header 'Access-Control-Allow-Methods';
        proxy_hide_header 'Access-Control-Allow-Headers';
        proxy_hide_header 'Access-Control-Allow-Credentials';

        # Apunta al nuevo proyecto de Supabase Cloud
        proxy_pass https://djwlchgkeeeqfkreebgq.supabase.co;
        proxy_ssl_server_name on;
        proxy_set_header Host djwlchgkeeeqfkreebgq.supabase.co;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 50M;
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, PATCH, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization, apikey, x-client-info, x-supabase-api-version' always;
    }
}
